query normalData {
  pokemons (limit: 15) {
    results {
      id
      name
    }
  }
}
query variData ($id: String!) {
  evolutionChain (id: $id) {
    response
  }
}
query limitData ($limit: Int) {
  pokemons (limit: $limit) {
    results {
      id
      name
    }
  }
}
